version: '1'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=report
    volumes:
      - data:/home/data
    networks:
      - net
    ports:
      - 5432:5432
  web:
    build: .
    networks:
      - net
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - REACT_APP_CHAT_URL=http://localhost:8080/chat
      - PORT=8080
networks:
  net: {}
volumes:
  data: {}